### ISSUE TITLE
error

### ISSUE THREAD

**Issue by malikshi** [KINGSABRI/chkdfront#1]
```
[ ✖ ] /usr/local/bin/chkdfront Exception
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix/rule.rb:126:in `count'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix/rule.rb:126:in `initialize'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix/rule.rb:117:in `new'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix/rule.rb:117:in `build'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix/rule.rb:332:in `factory'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix/list.rb:91:in `block (2 levels) in parse'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix/list.rb:73:in `each_line'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix/list.rb:73:in `block in parse'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix/list.rb:105:in `initialize'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix/list.rb:72:in `new'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix/list.rb:72:in `parse'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix/list.rb:49:in `default'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix.rb:67:in `parse'
/var/lib/gems/2.3.0/gems/public_suffix-3.0.3/lib/public_suffix.rb:140:in `domain'
/var/lib/gems/2.3.0/gems/addressable-2.6.0/lib/addressable/uri.rb:1195:in `domain'
/var/lib/gems/2.3.0/gems/adomain-0.1.1/lib/adomain.rb:70:in `parse_for_domain'
/var/lib/gems/2.3.0/gems/adomain-0.1.1/lib/adomain.rb:22:in `domain'
/var/lib/gems/2.3.0/gems/chkdfront-1.0.2/lib/chkdfront/cli_operations.rb:70:in `find_provider'
/var/lib/gems/2.3.0/gems/chkdfront-1.0.2/bin/chkdfront:131:in `<top (required)>'
/usr/local/bin/chkdfront:23:in `load'
/usr/local/bin/chkdfront:23:in `<main>'
```

**Comment by KINGSABRI** [comment]
Hi, 
Would you tell me what switches you've used to get this error? I need to reproduce the error
